import openai

with open('hidden.txt') as file:
    openai.api_key = file.read()


def get_api_response(prompt: str) -> str | None:
    """
    Sends a prompt string to the OpenAI API and returns a response string.

    :param prompt: A string representing the prompt to send to the OpenAI API.
    :return: A string representing the response generated by the OpenAI API, or None if there is an error.
    """
    text: str | None = None

    try:
        response: dict = openai.Completion.create(
            model='text-davinci-003',
            prompt=prompt,
            temperature=0.9,
            max_tokens=150,
            top_p=1,
            frequency_penalty=0,
            presence_penalty=0.6,
            stop=[' Human:', ' AI:']
        )

        choices: dict = response.get('choices')[0]
        text = choices.get('text')

    except Exception as e:
        print('Error:', e)

    return text


def update_list(message: str, prompt_list: list[str]):
    """
    Updates the prompt list with a new message.

    :param message: A string representing the new message to add to the prompt list.
    :param prompt_list: A list of strings representing the previous messages in the conversation.
    """
    prompt_list.append(message)


def create_prompt(message: str, prompt_list: list[str]) -> str:
    """
    Creates a new prompt string by concatenating the prompt list with a new message.

    :param message: A string representing the new message to add to the prompt list.
    :param prompt_list: A list of strings representing the previous messages in the conversation.
    :return: A string representing the prompt to send to the OpenAI API.
    """
    prompt_message: str = f'\nHuman: {message}'
    update_list(prompt_message, prompt_list)
    prompt: str = ''.join(prompt_list)
    return prompt


def get_bot_response(message: str, prompt_list: list[str]) -> str:
    """
    Generates a bot response by sending a prompt string to the OpenAI API.

    :param message: A string representing the user message to respond to.
    :param prompt_list: A list of strings representing the previous messages in the conversation.
    :return: A string representing the bot response to the user message.
    """
    prompt: str = create_prompt(message, prompt_list)
    bot_response: str = get_api_response(prompt)

    if bot_response:
        update_list(bot_response, prompt_list)
        pos: int = bot_response.find('\nAI: ')
        bot_response = bot_response[pos + 5:]
    else:
        bot_response = 'Something went wrong...'

    return bot_response


def main():
    """
    Defines the initial prompt list and starts a loop that waits for user input and generates bot responses.
    """
    prompt_list: list[str] = ['You are a customer care agent of a travel agency',
                              '\nHuman: What time is it?', '\nAI: It is 12:00, ye']

    while True:
        user_input: str = input('You: ')
        response: str = get_bot_response(user_input, prompt_list)
        print(f'Bot: {response}')
        # print(prompt_list)


if __name__ == '__main__':
    main()

